# Generated by Django 4.2.7 on 2025-06-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('TOGGLE', 'Toggle'), ('AUTO_DISABLE', 'Auto Disable')], max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_status', models.BooleanField(default=False)),
                ('new_status', models.BooleanField(default=False)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='flags.flag')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependency_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_as_parent', to='flags.flag')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_as_child', to='flags.flag')),
            ],
            options={
                'unique_together': {('flag', 'dependency_on')},
            },
        ),
    ]
