# Generated by Django 4.2.7 on 2025-06-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(blank=True, to='flags.featureflag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('TOGGLE', 'Toggle'), ('AUTO_DISABLE', 'Auto Disable')], max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='flags.featureflag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
